import Head from 'next/head';
import Exercise, {
  NavigationLink,
  SolutionLink,
} from '~/components/chore/Navigation';
import { prisma } from '~/db/prisma';

// const inter = Inter({ subsets: ['latin'] });

export default function Home({ tweetId }: { tweetId: string }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col gap-4 p-2">
        <h1>Welcome to the twitter app !</h1>
        <div className="mt-4 flex flex-col gap-8">
          <Exercise number={1} solutionCount={3} />
          <Exercise number={2} solutionCount={4}>
            <SolutionLink number={2} solution="3-bonus" />
          </Exercise>

          <Exercise number={3} solutionCount={2} />
          <NavigationLink blue href={`/routing/tweets/${tweetId}`}>
            Exercice 4
          </NavigationLink>
          <div className="flex flex-col gap-2">
            <NavigationLink blue href={`/exercices/rules`}>
              Exercice 5
            </NavigationLink>

            <NavigationLink href={`/solutions/rules`}>
              Solution 5
            </NavigationLink>
          </div>
          <div className="flex flex-col gap-2">
            <NavigationLink blue href={`/6/users`}>
              Exercice 6
            </NavigationLink>
          </div>
        </div>
      </div>
    </>
  );
}

export const getStaticProps = async () => {
  const tweetId = await prisma.tweet.findFirst({
    select: {
      id: true,
    },
  });

  return {
    props: {
      tweetId: tweetId?.id,
    },
  };
};
